### ISSUE TITLE
Chisel 2 Support

### ISSUE THREAD

**Issue by Mictali** [RedGear/Geocraft#5]
Geocraft has a check for the Chisel mod to activate compatibility but it doesn't work with the Chisel 2 update being maintained by TheCricket26.   Could you add to the compatibility setup a check for the class com.cricketcraft.chisel.compat.Compatibility along with the current check for info.jbcs.minecraft.chisel.Compatibility?

**Comment by egeis** [comment]
I submitted a pull request with the change you need for compatibility.
